import os
from pathlib import Path

from dotenv import load_dotenv

ROOT_DIR = Path(__file__).resolve().parents[1]
ENV_PATH = (ROOT_DIR / ".env").resolve()

load_dotenv(dotenv_path=str(ENV_PATH), override=False)

def env_str(name: str, default: str = "") -> str:
    return os.getenv(name, default)


KALSHI_API_KEY = env_str("KALSHI_API_KEY").strip()
API_KEY = KALSHI_API_KEY or ""
BASE_URL = "https://api.elections.kalshi.com/trade-api/v2"


def env_bool(name, default):
    raw = os.getenv(name)
    if raw is None:
        return default
    return str(raw).strip().lower() in {"1", "true", "yes", "on", "y", "t"}


def env_float(name, default):
    raw = os.getenv(name)
    if raw is None or str(raw).strip() == "":
        return default
    try:
        return float(raw)
    except Exception:
        return default


def env_int(name, default):
    raw = os.getenv(name)
    if raw is None or str(raw).strip() == "":
        return default
    try:
        return int(float(raw))
    except Exception:
        return default


COLOR_LOGS = os.getenv("COLOR_LOGS", "true").lower() == "true"
OFFLINE_DEBUG = os.getenv("OFFLINE_DEBUG", "false").lower() == "true"
OFFLINE_LIFECYCLE_TEST = os.getenv("OFFLINE_LIFECYCLE_TEST", "false").lower() == "true"
OFFLINE_SCENARIO = os.getenv("OFFLINE_SCENARIO", "elite").lower()
OFFLINE_MODE = OFFLINE_DEBUG or OFFLINE_LIFECYCLE_TEST

MIN_EV = 0.02
MIN_EV_T2 = 0.005
MIN_EDGE_GAP = 0.015
TIER2_SIZE_MULT = 0.5
PAPER_START_BALANCE = env_float("PAPER_START_BALANCE", 90.0)
BANKROLL = PAPER_START_BALANCE
CAP_FAMILY_PCT = 0.25
CAP_SHORT_PCT = 0.25
CAP_LONG_PCT = 0.20
MIN_PRESSURE = env_float("MIN_PRESSURE", 0.48)
MIN_PRESSURE_ENTRY = env_float("MIN_PRESSURE_ENTRY", 0.48)
MIN_PRESSURE_TO_ENTER = env_float("MIN_PRESSURE_TO_ENTER", 0.48)
NO_TRADE_MIN_PRESSURE = env_float("NO_TRADE_MIN_PRESSURE", 0.48)
ALLOW_ENTRY_IN_NO_TRADE = env_bool("ALLOW_ENTRY_IN_NO_TRADE", True)
ELITE_ENTRY_ALLOW_IN_NO_TRADE = env_bool("ELITE_ENTRY_ALLOW_IN_NO_TRADE", False)
ELITE_MIN_PRESSURE = env_float("ELITE_MIN_PRESSURE", 0.50)
CHF_MODE = env_bool("CHF_MODE", True)
CHF_MIN_PRESSURE = env_float("CHF_MIN_PRESSURE", 0.45)
BASE_PRESSURE = 0.25
MIN_PRESSURE_ACCEL = env_float("MIN_PRESSURE_ACCEL", 0.00)
MAX_ENTRY_SPREAD = env_float("MAX_ENTRY_SPREAD", 0.10)
CHF_MAX_SPREAD = env_float("CHF_MAX_SPREAD", 0.08)
MAX_HARD_SPREAD = env_float("MAX_HARD_SPREAD", 0.12)
MAX_SPREAD_HARD = env_float("MAX_SPREAD_HARD", 0.45)
MAX_SPREAD_SOFT = env_float("MAX_SPREAD_SOFT", 0.20)
MIN_LIQUIDITY_SCORE = env_float("MIN_LIQUIDITY_SCORE", 0.35)
MIN_BOOK_DEPTH_SCORE = env_float("MIN_BOOK_DEPTH_SCORE", 0.20)
MIN_BOOK_SIZE = env_int("MIN_BOOK_SIZE", 5)
FINAL_ENTRY_MAX_SPREAD = env_float("FINAL_ENTRY_MAX_SPREAD", 0.04)
FINAL_ENTRY_MIN_TOUCH = env_int("FINAL_ENTRY_MIN_TOUCH", 10)
ELITE_MAX_SPREAD = env_float("ELITE_MAX_SPREAD", 0.04)
ELITE_MIN_TOUCH = env_int("ELITE_MIN_TOUCH", 10)
MIN_EDGE = env_float("MIN_EDGE", 0.008)
CHF_MIN_EDGE = env_float("CHF_MIN_EDGE", 0.02)
YES_MIN_ENTRY_PRICE = env_float("YES_MIN_ENTRY_PRICE", 0.05)
NO_MIN_ENTRY_PRICE = env_float("NO_MIN_ENTRY_PRICE", 0.10)
CHEAP_ENTRY_PRICE_MAX = env_float("CHEAP_ENTRY_PRICE_MAX", 0.08)
CHEAP_POSITION_USD_MAX = env_float("CHEAP_POSITION_USD_MAX", 1.00)
CHEAP_NEG_PNL_EXIT = env_float("CHEAP_NEG_PNL_EXIT", -0.01)
CHEAP_MAX_HOLD_SECS = env_int("CHEAP_MAX_HOLD_SECS", 180)
DEAD_PRICE_MAX = env_float("DEAD_PRICE_MAX", 0.10)
DEAD_SIZE_MAX = env_float("DEAD_SIZE_MAX", 1.50)
DEAD_PNL = env_float("DEAD_PNL", -0.008)
DEAD_HOLD_SECS = env_int("DEAD_HOLD_SECS", 120)
MODEL_VOL = env_float("MODEL_VOL", 0.60)
MAX_TRADE_SPREAD = env_float("MAX_TRADE_SPREAD", 0.05)
MIN_VOLUME = env_int("MIN_VOLUME", 1000)
MIN_ENTRY_SCORE = env_float("MIN_ENTRY_SCORE", 0.10)
MIN_ALLOC_SCORE = env_float("MIN_ALLOC_SCORE", 0.20)
ROTATION_MIN_ALPHA = env_float("ROTATION_MIN_ALPHA", 0.18)
ROTATION_MIN_EDGE_ADVANTAGE = env_float("ROTATION_MIN_EDGE_ADVANTAGE", 0.10)
ROTATION_MIN_QUALITY_ADVANTAGE = env_float("ROTATION_MIN_QUALITY_ADVANTAGE", 0.05)
ROTATION_STALE_HELD_SECS = env_int("ROTATION_STALE_HELD_SECS", 120)
ROTATION_MAX_PROTECTED_USD = env_float("ROTATION_MAX_PROTECTED_USD", 3.00)
ROTATION_CHEAP_ENTRY_MAX = env_float("ROTATION_CHEAP_ENTRY_MAX", 0.10)
ROTATION_MIN_HELD_SECS = env_int("ROTATION_MIN_HELD_SECS", 45)
ROTATION_PROTECT_WINNERS = env_bool("ROTATION_PROTECT_WINNERS", True)
ROTATION_STRONG_EXTRA_ALPHA = env_float("ROTATION_STRONG_EXTRA_ALPHA", 0.10)
ROTATION_COOLDOWN_SECS = env_int("ROTATION_COOLDOWN_SECS", 60)
STALKER_MIN = env_float("STALKER_MIN", 0.54)
STALKER_SIZE_MULT = env_float("STALKER_SIZE_MULT", 0.35)
ENTRY_COOLDOWN_SECS = env_int("ENTRY_COOLDOWN_SECS", 90)
POST_EXIT_COOLDOWN_SECS = env_int("POST_EXIT_COOLDOWN_SECS", 15)
MAX_TRADE_SIZE = env_float("MAX_TRADE_SIZE", 4.00)
MAX_TRADE = MAX_TRADE_SIZE
MAX_LOSS_PER_TRADE = env_float("MAX_LOSS_PER_TRADE", 2.0)
CYCLE_SECS = 10
TP_PNL = env_float("TP_PNL", 0.02)
STOP_PNL = env_float("STOP_PNL", -0.015)
TAKE_PROFIT = TP_PNL
STOP_LOSS = STOP_PNL
CHF_TIME_STOP_SECS = env_int("CHF_TIME_STOP_SECS", 240)
TIME_STOP_SECS = CHF_TIME_STOP_SECS
MAX_HOLD_SECONDS = 60
MIN_HOLD_SECONDS = env_int("MIN_HOLD_SECONDS", 30)
MIN_EARLY_LOSS_HOLD_SECONDS = env_int("MIN_EARLY_LOSS_HOLD_SECONDS", 25)
CATASTROPHIC_STOP = env_float("CATASTROPHIC_STOP", -0.05)
CATASTROPHIC_STOP_LOSS = env_float("CATASTROPHIC_STOP_LOSS", -0.070)
EARLY_PROTECT_MIN_HOLD = env_int("EARLY_PROTECT_MIN_HOLD", 45)
EXTREME_STOP_LOSS = CATASTROPHIC_STOP
EXIT_WARMUP_SECONDS = env_int("EXIT_WARMUP_SECONDS", 480)
EXIT_MATURE_SECONDS = env_int("EXIT_MATURE_SECONDS", 1680)
PRESSURE_EXIT_CONFIRM_CYCLES = env_int("PRESSURE_EXIT_CONFIRM_CYCLES", 2)
PRESSURE_EXIT_GRACE_SECONDS = env_int("PRESSURE_EXIT_GRACE_SECONDS", 45)
TRAIL_ARM_PNL = env_float("TRAIL_ARM_PNL", 0.015)
TRAIL_MIN_LOCK_PNL = env_float("TRAIL_MIN_LOCK_PNL", 0.004)
PRESSURE_EXIT = env_float("PRESSURE_EXIT", 0.50)
MOMENTUM_BREAK_CROWD_DROP = env_float("MOMENTUM_BREAK_CROWD_DROP", 0.12)
HFT_TAKE_PROFIT = TP_PNL
HFT_STOP_LOSS = STOP_PNL
HFT_COOLDOWN_SECS = POST_EXIT_COOLDOWN_SECS
HFT_SERIES = {"KXBTC", "KXETH"}
HFT_MAX_HOURS = 1.0
MIN_CROWD = 0.85
MAX_CROWD = 0.97
MAX_NEW_TRADES_PER_CYCLE = env_int("MAX_NEW_TRADES_PER_CYCLE", 10)
CHF_MAX_NEW_TRADES_PER_CYCLE = env_int("CHF_MAX_NEW_TRADES_PER_CYCLE", 2)
MAX_OPEN_POSITIONS = env_int("MAX_OPEN_POSITIONS", 3)
CHF_MAX_POSITIONS_TOTAL = env_int("CHF_MAX_POSITIONS_TOTAL", 4)
MAX_POSITIONS_PER_CLUSTER = env_int("MAX_POSITIONS_PER_CLUSTER", 2)
MAX_CLUSTER_HARD_CAP = env_int("MAX_CLUSTER_HARD_CAP", 3)
MAX_REINFORCE_PER_TICKER = env_int("MAX_REINFORCE_PER_TICKER", 1)
REINFORCE_MIN_KILLER_SCORE = env_float("REINFORCE_MIN_KILLER_SCORE", 0.67)
REINFORCE_MIN_EDGE = env_float("REINFORCE_MIN_EDGE", 0.45)
REINFORCE_SIZE_MULT = env_float("REINFORCE_SIZE_MULT", 0.50)
REINFORCE_MIN_HOLD_SECS = env_int("REINFORCE_MIN_HOLD_SECS", 45)
STALE_CONVICTION_MIN_HOLD = env_int("STALE_CONVICTION_MIN_HOLD", 180)
STALE_BREAK_MIN_HOLD = env_int("STALE_BREAK_MIN_HOLD", 240)
MAX_POSITIONS_PER_SERIES = env_int("MAX_POSITIONS_PER_SERIES", MAX_POSITIONS_PER_CLUSTER)
CHF_MAX_POSITIONS_PER_SERIES = env_int("CHF_MAX_POSITIONS_PER_SERIES", 1)
MAX_CAPITAL_PER_CYCLE_PCT = env_float("MAX_CAPITAL_PER_CYCLE_PCT", 0.35)
MAX_CAPITAL_PER_TRADE_PCT = env_float("MAX_CAPITAL_PER_TRADE_PCT", 0.15)
MAX_ROTATIONS_PER_CYCLE = env_int("MAX_ROTATIONS_PER_CYCLE", 1)
ROTATION_ENABLED = env_bool("ROTATION_ENABLED", False)  # set True to re-enable
# NO-side hold extension — multiplies time_stop and early-protect window for NO trades.
# 2.0 = hold twice as long before a time/momentum exit fires. Set 1.0 to disable.
NO_SIDE_HOLD_MULT = env_float("NO_SIDE_HOLD_MULT", 2.0)
# When True, suppresses momentum_break and conviction_decay exits on NO-side trades,
# giving them the full time window to resolve. Hard/catastrophic stops still fire.
NO_SIDE_SUPPRESS_SOFT_EXITS = env_bool("NO_SIDE_SUPPRESS_SOFT_EXITS", True)
CHF_ACTIVE_LOW = env_float("CHF_ACTIVE_LOW", 0.08)
CHF_ACTIVE_HIGH = env_float("CHF_ACTIVE_HIGH", 0.92)
CHURN_BLOCK_SECS = env_int("CHURN_BLOCK_SECS", 30)
BOOK_IMBALANCE_WEIGHT = env_float("BOOK_IMBALANCE_WEIGHT", 0.30)
PRESSURE_WEIGHT = env_float("PRESSURE_WEIGHT", 0.35)
EDGE_WEIGHT = env_float("EDGE_WEIGHT", 0.20)
LIQUIDITY_WEIGHT = env_float("LIQUIDITY_WEIGHT", 0.15)
USE_REGIME_FILTER = env_bool("USE_REGIME_FILTER", True)
USE_TIME_STOP = env_bool("USE_TIME_STOP", True)
USE_TRAIL_PROTECT = env_bool("USE_TRAIL_PROTECT", True)
TRAIL_TRIGGER_PNL = env_float("TRAIL_TRIGGER_PNL", 0.006)
TRAIL_GIVEBACK = env_float("TRAIL_GIVEBACK", 0.003)
WEAK_BOOK_SKIP = env_bool("WEAK_BOOK_SKIP", True)
NO_TRADE_IF_SPOT_MISSING = env_bool("NO_TRADE_IF_SPOT_MISSING", False)
LOG_DIAGNOSTICS = env_bool("LOG_DIAGNOSTICS", True)
LOG_SKIP_REASONS = env_bool("LOG_SKIP_REASONS", True)
LOG_ENTRY_COMPONENTS = env_bool("LOG_ENTRY_COMPONENTS", True)
COMPACT_LOGS = env_bool("COMPACT_LOGS", True)
DEBUG = env_bool("DEBUG", False)
PAPER_STATE_RESET = env_bool("PAPER_STATE_RESET", False)
HARD_SPREAD_FLOOR = env_float("HARD_SPREAD_FLOOR", 0.04)
HARD_SPREAD_CEIL = env_float("HARD_SPREAD_CEIL", 0.08)
TOUCH_REQ_TIGHT = env_int("TOUCH_REQ_TIGHT", 10)
TOUCH_REQ_MID = env_int("TOUCH_REQ_MID", 25)
TOUCH_REQ_WIDE = env_int("TOUCH_REQ_WIDE", 50)
MAX_T3_PER_CYCLE = env_int("MAX_T3_PER_CYCLE", 1)
